/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ua.itea.patiy.yevgen.domino;

import java.awt.Color;
import java.awt.Dimension;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import ua.itea.patiy.yevgen.domino.panels.Bazar;
import ua.itea.patiy.yevgen.domino.panels.Field;
import ua.itea.patiy.yevgen.domino.panels.Player;

/**
 *
 * @author yevgen
 */
public class Main extends JFrame {

    /**
     * 
     */
    private static final long serialVersionUID = -8260728118527482348L;

    @Override
    public void setTitle(String title) {
        super.setTitle(title); // To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        bazar = new Bazar();
        you = new Player();
        me = new Player();
        field = new Field();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(0, 204, 102));
        setMinimumSize(new Dimension(1300, 720));
        setName("window"); // NOI18N
        setResizable(false);
        setSize(new Dimension(1300, 720));
        getContentPane().setLayout(new AbsoluteLayout());

        bazar.setBackground(new Color(0, 102, 51));
        bazar.setLayout(new AbsoluteLayout());
        getContentPane().add(bazar, new AbsoluteConstraints(1200, 0, 100, 720));
        bazar.initBazar();

        you.setBackground(new Color(0, 102, 51));
        you.setTitle(" Поле гравця " + Game.enemyname + " ");
        you.setPlayerName(Game.enemyname, Const.ROBOT);
        you.setLayout(new AbsoluteLayout());
        getContentPane().add(you, new AbsoluteConstraints(0, 0, 1200, 100));

        me.setBackground(new Color(0, 102, 51));
        me.setTitle(" Поле гравця " + Game.myname + " ");
        me.setPlayerName(Game.myname, Const.HUMAN);
        me.setLayout(new AbsoluteLayout());
        getContentPane().add(me, new AbsoluteConstraints(0, 620, 1200, 100));

        field.setBackground(new Color(0, 102, 51));
        field.setTitle(" Це ігрове поле. Для початку беріть з базара 7 каменів. Те ж саме зробить і супротивник "
                + Game.enemyname + " ");
        field.setLayout(new AbsoluteLayout());
        getContentPane().add(field, new AbsoluteConstraints(0, 100, 1200, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Creates new form Domino
     *
     */
    public Main() {

        URL iconURL = getClass().getResource("/img/logos/domino.png"); // иконка приложения
        ImageIcon icon = new ImageIcon(iconURL);
        Game game = new Game();

        setTitle(game.getTitle()); // заголовок окна
        setIconImage(icon.getImage()); // иконка
        initComponents(); // интерфейс игры
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
        } catch (InstantiationException ex) {
        } catch (IllegalAccessException ex) {
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static Bazar bazar;
    protected static Field field;
    protected static Player me;
    protected static Player you;
    // End of variables declaration//GEN-END:variables
}
